name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g codecov nyc
      - run: yarn install
      - run: yarn build
      - run: LANG=en_CA TZ=America/Vancouver yarn test
      - run: LANG=en_US TZ=America/Los_Angeles yarn test
      - run: LANG=sw_KE TZ=Africa/Nairobi yarn test
      - run: LANG=en_KI TZ=Pacific/Kiritimati yarn test
      - run: LANG=jp_JP TZ=Asia/Tokyo yarn test-ci
      - run: nyc report --reporter=json && codecov -t ${{ secrets.CODECOV_REPO_TOKEN }} -f coverage/*.json
